site_name: OpenSavvy
site_author: OpenSavvy & contributors
site_description: >
  Open source projects with a deep focus on quality, automation and security.

theme:
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    # - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  icon:
    edit: material/pencil
    view: material/eye
  logo: assets/logo.svg
  favicon: assets/logo.svg
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: "System theme (click to switch to light)"
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: "Light theme (click to switch to dark)"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: "Dark theme (click to switch to system)"

plugins:
  - social

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true

edit_uri: edit/main/docs/website/docs

use_directory_urls: false

nav:
  - Home: index.md

  - Kotlin Multiplatform:
      - libraries/overview.md
      - libraries/supported-platforms.md
      - Groundwork:
          - libraries/groundwork/pedestal-progress.md
          - libraries/groundwork/pedestal-state.md
          - libraries/groundwork/pedestal-cache.md
          - libraries/groundwork/backbone.md
          - libraries/groundwork/prepared.md
          - libraries/groundwork/spine.md
          - libraries/groundwork/indolent.md
          - libraries/groundwork/sentier.md
      - User interface:
          - libraries/ui/decouple.md
          - libraries/ui/lazy-layouts.md
          - libraries/ui/material3.md
      - Gradle plugins:
          - libraries/gradle/vite.md
          - libraries/gradle/kjs-resources.md

  - System administration:
      - system/overview.md
      - system/packager.md
      - system/toolkit.md
      - system/aur-template.md

  - Automation:
      - automation/overview.md
      - automation/containers.md
      - automation/gradle-conventions.md
      - automation/gitlab-kts.md
      - automation/gitlab-templates.md
